[package]
name = "fishtank"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
rand = "0.9.2"
rayon = "1.11.0"

[dev-dependencies]
criterion = "0.8.1"

[[bench]]
name = "sim_benchmark"
harness = false

[[bench]]
name = "render_benchmark"
harness = false
